# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ui_srrf.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 703)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI SC")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.browse_tif_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_tif_button.setObjectName("browse_tif_button")
        self.horizontalLayout_7.addWidget(self.browse_tif_button)
        self.browse_folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_folder_button.setObjectName("browse_folder_button")
        self.horizontalLayout_7.addWidget(self.browse_folder_button)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 14))
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.mag_spin_box = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.mag_spin_box.setMinimumSize(QtCore.QSize(0, 14))
        self.mag_spin_box.setMinimum(2.0)
        self.mag_spin_box.setMaximum(20.0)
        self.mag_spin_box.setSingleStep(0.5)
        self.mag_spin_box.setProperty("value", 4.0)
        self.mag_spin_box.setObjectName("mag_spin_box")
        self.gridLayout_4.addWidget(self.mag_spin_box, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(0, 14))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.rad_spin_box = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rad_spin_box.setMinimumSize(QtCore.QSize(0, 14))
        self.rad_spin_box.setMinimum(0.1)
        self.rad_spin_box.setMaximum(20.0)
        self.rad_spin_box.setSingleStep(0.1)
        self.rad_spin_box.setProperty("value", 0.4)
        self.rad_spin_box.setObjectName("rad_spin_box")
        self.gridLayout_4.addWidget(self.rad_spin_box, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(0, 14))
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.axes_spin_box = QtWidgets.QSpinBox(self.groupBox)
        self.axes_spin_box.setMinimumSize(QtCore.QSize(0, 14))
        self.axes_spin_box.setMinimum(2)
        self.axes_spin_box.setMaximum(12)
        self.axes_spin_box.setProperty("value", 6)
        self.axes_spin_box.setObjectName("axes_spin_box")
        self.gridLayout_4.addWidget(self.axes_spin_box, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(0, 14))
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.n_frame_spin_box = QtWidgets.QSpinBox(self.groupBox)
        self.n_frame_spin_box.setMinimumSize(QtCore.QSize(0, 14))
        self.n_frame_spin_box.setMinimum(1)
        self.n_frame_spin_box.setMaximum(10000)
        self.n_frame_spin_box.setProperty("value", 1)
        self.n_frame_spin_box.setObjectName("n_frame_spin_box")
        self.gridLayout_4.addWidget(self.n_frame_spin_box, 3, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(13, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dc_checkbox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dc_checkbox.sizePolicy().hasHeightForWidth())
        self.dc_checkbox.setSizePolicy(sizePolicy)
        self.dc_checkbox.setObjectName("dc_checkbox")
        self.verticalLayout_3.addWidget(self.dc_checkbox)
        self.iw_checkbox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iw_checkbox.sizePolicy().hasHeightForWidth())
        self.iw_checkbox.setSizePolicy(sizePolicy)
        self.iw_checkbox.setChecked(True)
        self.iw_checkbox.setObjectName("iw_checkbox")
        self.verticalLayout_3.addWidget(self.iw_checkbox)
        self.gw_checkbox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gw_checkbox.sizePolicy().hasHeightForWidth())
        self.gw_checkbox.setSizePolicy(sizePolicy)
        self.gw_checkbox.setObjectName("gw_checkbox")
        self.verticalLayout_3.addWidget(self.gw_checkbox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.trac_order_spin_box = QtWidgets.QSpinBox(self.groupBox1)
        self.trac_order_spin_box.setMinimum(2)
        self.trac_order_spin_box.setMaximum(4)
        self.trac_order_spin_box.setObjectName("trac_order_spin_box")
        self.gridLayout_3.addWidget(self.trac_order_spin_box, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(71, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.tra_radio_button = QtWidgets.QRadioButton(self.groupBox1)
        self.tra_radio_button.setObjectName("tra_radio_button")
        self.gridLayout_3.addWidget(self.tra_radio_button, 0, 0, 1, 1)
        self.trac_delay_spin_box = QtWidgets.QSpinBox(self.groupBox1)
        self.trac_delay_spin_box.setMinimum(0)
        self.trac_delay_spin_box.setMaximum(100)
        self.trac_delay_spin_box.setProperty("value", 1)
        self.trac_delay_spin_box.setObjectName("trac_delay_spin_box")
        self.gridLayout_3.addWidget(self.trac_delay_spin_box, 1, 3, 1, 1)
        self.trac_radio_button = QtWidgets.QRadioButton(self.groupBox1)
        self.trac_radio_button.setCheckable(True)
        self.trac_radio_button.setChecked(True)
        self.trac_radio_button.setObjectName("trac_radio_button")
        self.gridLayout_3.addWidget(self.trac_radio_button, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(31, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 4, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pyqtimv = ImageView(self.centralwidget)
        self.pyqtimv.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyqtimv.sizePolicy().hasHeightForWidth())
        self.pyqtimv.setSizePolicy(sizePolicy)
        self.pyqtimv.setMinimumSize(QtCore.QSize(256, 256))
        self.pyqtimv.setObjectName("pyqtimv")
        self.horizontalLayout_4.addWidget(self.pyqtimv)
        self.pyqtimv_2 = ImageView(self.centralwidget)
        self.pyqtimv_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyqtimv_2.sizePolicy().hasHeightForWidth())
        self.pyqtimv_2.setSizePolicy(sizePolicy)
        self.pyqtimv_2.setMinimumSize(QtCore.QSize(256, 256))
        self.pyqtimv_2.setObjectName("pyqtimv_2")
        self.horizontalLayout_4.addWidget(self.pyqtimv_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 24))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 24))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.reset_button.setBaseSize(QtCore.QSize(0, 0))
        self.reset_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_8.addWidget(self.reset_button)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.start_button.setBaseSize(QtCore.QSize(0, 0))
        self.start_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_8.addWidget(self.start_button)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.save_button.setBaseSize(QtCore.QSize(0, 0))
        self.save_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.save_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_8.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tra_radio_button.clicked['bool'].connect(self.trac_order_spin_box.setDisabled)
        self.trac_radio_button.clicked['bool'].connect(self.trac_delay_spin_box.setEnabled)
        self.trac_radio_button.clicked['bool'].connect(self.trac_order_spin_box.setEnabled)
        self.tra_radio_button.clicked['bool'].connect(self.trac_delay_spin_box.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SRRF_cupy"))
        self.label_3.setText(_translate("MainWindow", "File"))
        self.browse_tif_button.setText(_translate("MainWindow", "Open TIF"))
        self.browse_folder_button.setText(_translate("MainWindow", "Open Folder"))
        self.groupBox.setTitle(_translate("MainWindow", "Spacial Analysis"))
        self.label_6.setText(_translate("MainWindow", "Radiality Magnification"))
        self.label_7.setText(_translate("MainWindow", "Ring radius(px)"))
        self.label_9.setText(_translate("MainWindow", "Axes in Ring"))
        self.label_10.setText(_translate("MainWindow", "Sum up every n frames"))
        self.dc_checkbox.setText(_translate("MainWindow", "Do Drift-Correction(slow, for high density)"))
        self.iw_checkbox.setText(_translate("MainWindow", "Do Intensity Weighting"))
        self.gw_checkbox.setText(_translate("MainWindow", "Do Gradient Weighting(for low density)"))
        self.groupBox1.setTitle(_translate("MainWindow", "Temporal Analysis"))
        self.label_13.setText(_translate("MainWindow", "TRAC Order"))
        self.label_14.setText(_translate("MainWindow", "TRAC Delay"))
        self.tra_radio_button.setText(_translate("MainWindow", "Temporal Radiality Average(TRA)"))
        self.trac_radio_button.setText(_translate("MainWindow", "Temporal Radiality Auto-Correlations(TRAC)"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.save_button.setText(_translate("MainWindow", "Save"))

from pyqtgraph import ImageView
